spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.driver
    username: root
    password: 2659201192
    url: jdbc:mysql://localhost:3306/community?useunicode=true&characterencoding=utf-8&autoreconnect=true&userssl=true&servertimezone=asia/shanghai

